# Generated by Django 3.2.2 on 2021-05-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=32)),
                ('nombre', models.CharField(max_length=32)),
                ('apellido_paterno', models.CharField(max_length=32)),
                ('apellido_materno', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('num_telefono', models.IntegerField(max_length=10)),
                ('tipo', models.CharField(max_length=32)),
            ],
        ),
    ]
