# Generated by Django 3.2.2 on 2021-05-21 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='num_telefono',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Talleres',
            fields=[
                ('id_taller', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.administradores')),
            ],
        ),
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_control', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=32)),
                ('apellido_paterno', models.CharField(max_length=32)),
                ('apellido_materno', models.CharField(max_length=32)),
                ('carrera', models.CharField(max_length=32)),
                ('grupo', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('num_telefono', models.IntegerField()),
                ('id_taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talleres.talleres')),
            ],
        ),
    ]
