# Generated by Django 3.2.2 on 2021-05-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_auto_20210521_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='apellido_materno',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='apellido_paterno',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='num_telefono',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='apellido_materno',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='apellido_paterno',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='num_telefono',
            field=models.BigIntegerField(),
        ),
    ]
